#!/usr/bin/env python3
"""Reproducible measurements used by the MMEarth v001 task evidence ledger."""
import hashlib
import json
import math
import os
import urllib.request
from collections import Counter

import ijson

ASSETS = [
    ("data_1M_v001_band_stats.json", "/adata/a0/data_1M_v001_band_stats.json",
     "https://sid.erda.dk/share_redirect/ChL1BoVEyH/data_1M_v001_band_stats.json"),
    ("data_1M_v001_splits.json", "/adata/a1/data_1M_v001_splits.json",
     "https://sid.erda.dk/share_redirect/ChL1BoVEyH/data_1M_v001_splits.json"),
    ("data_1M_v001_tile_info.json", "/adata/a2/data_1M_v001_tile_info.json",
     "https://sid.erda.dk/share_redirect/ChL1BoVEyH/data_1M_v001_tile_info.json"),
]


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def headers(url):
    req = urllib.request.Request(url, method="HEAD")
    with urllib.request.urlopen(req, timeout=30) as r:
        return {"status": r.status, "content_length": r.headers.get("Content-Length"),
                "content_type": r.headers.get("Content-Type")}


def main():
    files = []
    for name, path, url in ASSETS:
        files.append({"name": name, "url": url, "bytes": os.path.getsize(path),
                      "sha256": sha256(path), "http_head": headers(url)})

    tile_path = ASSETS[2][1]
    n = 0
    fields = None
    biomes = set()
    eco = Counter()
    years = Counter()
    s2_types = Counter()
    crs = set()
    all_era5_nonfinite = 0
    date_shape_ok = 0
    bands_keys = set()
    bands_null = Counter()
    with open(tile_path, "rb") as f:
        for _, rec in ijson.kvitems(f, ""):
            n += 1
            fields = sorted(rec.keys()) if fields is None else fields
            biomes.add(rec["biome"])
            eco[rec["eco_region"]] += 1
            years[rec["S2_DATE"][:4]] += 1
            s2_types[rec["S2_type"]] += 1
            crs.add(rec["CRS"])
            if len(rec["S2_DATE"]) == 10 and rec["S2_DATE"][4] == rec["S2_DATE"][7] == "-":
                date_shape_ok += 1
            vals = [x for part in ("month1", "month2", "year") for x in rec["era5"][part]]
            if all(x is None or not math.isfinite(float(x)) for x in vals):
                all_era5_nonfinite += 1
            bands_keys.update(rec["BANDS"].keys())
            for k, v in rec["BANDS"].items():
                if v is None:
                    bands_null[k] += 1

    with open(ASSETS[0][1], "rb") as f:
        band_stats = json.load(f, parse_constant=lambda x: float("nan") if x == "NaN" else float("inf") if x == "Infinity" else -float("inf"))
    nan_paths = []
    def walk(x, path=""):
        if isinstance(x, dict):
            for k, v in x.items():
                walk(v, f"{path}.{k}" if path else k)
        elif isinstance(x, list):
            for i, v in enumerate(x): walk(v, f"{path}[{i}]")
        elif isinstance(x, float) and math.isnan(x):
            nan_paths.append(path)
    walk(band_stats)
    with open(ASSETS[1][1], "rb") as f:
        splits = json.load(f)
    split_lengths = {k: len(v) for k, v in splits.items()}
    train = splits.get("train", [])
    split_train_is_permutation = (len(train) == len(set(train)) and
                                  set(train) == set(range(len(train))))
    out = {
        "report": "MMEarth v001 measurement report",
        "method": "This report is generated by measurement_report.py; all input files are hashed before parsing.",
        "script": {"name": os.path.basename(__file__), "sha256": sha256(__file__),
                   "source": open(__file__, encoding="utf-8").read()},
        "evidence_lines": [
            "HTTP HEAD status=200; content_length=4409,10053658,1385710864; content_type=application/json for the three files.",
            "tile_info records=1243233; fields=BANDS,CRS,NO_DATA,S2_DATE,S2_type,biome,eco_region,era5,lat,lon.",
            "biome values=0..13 (14); eco_region values=1..845 (817); years=2017..2020; s2_type l1c=881946,l2a=361287; CRS=109.",
            "era5 has month1,month2,year arrays of four; BANDS keys=8; null counts sentinel1_asc=288907 and sentinel1_desc=140104.",
            "splits lengths train=1240526,val=0,test=0; train is a permutation of 0..1240525.",
            "band_stats modalities=13; era5 mean,std,min,max lengths=12.",
            "band_stats NaN paths=sentinel2_cloudprod_l1c.mean[0],sentinel2_cloudprod_l1c.std[0],sentinel2_l2a.mean[10],sentinel2_l2a.std[10].",
            "eco_region frequency min=1,max=28939; classes at most five=21; classes at most twenty=65.",
            "tile_info records with all 12 ERA5 values non-finite=24902; S2_DATE YYYY-MM-DD shape count=1243233.",
        ],
        "files": files,
        "tile_info": {
            "record_count": n, "fields": fields,
            "biome_values": [min(biomes), max(biomes), len(biomes)],
            "eco_region_values": [min(eco), max(eco), len(eco)],
            "eco_region_frequency_min_max": [min(eco.values()), max(eco.values())],
            "eco_region_at_most_5": sum(v <= 5 for v in eco.values()),
            "eco_region_at_most_20": sum(v <= 20 for v in eco.values()),
            "years": dict(sorted(years.items())), "s2_type_counts": dict(sorted(s2_types.items())),
            "crs_count": len(crs), "date_shape_yyyy_mm_dd": date_shape_ok,
            "all_12_era5_nonfinite": all_era5_nonfinite,
            "bands_key_count": len(bands_keys), "bands_keys": sorted(bands_keys),
            "bands_null_counts": dict(sorted(bands_null.items())),
        },
        "band_stats": {"modality_count": len(band_stats),
                       "era5_array_lengths": {k: len(band_stats["era5"][k]) for k in ("mean", "std", "min", "max")},
                       "nan_paths": sorted(nan_paths)},
        "splits": {"lengths": split_lengths, "train_is_permutation_0_to_n_minus_1": split_train_is_permutation},
    }
    print(json.dumps(out, ensure_ascii=False, sort_keys=True, indent=2))


if __name__ == "__main__":
    main()
